'use client'
import { useState, useCallback } from 'react'
import { useParams } from 'next/navigation'
import { supabase, slugToDate, buildQuestions, type QuizQuestion } from '@/lib/supabase'
import { Ring } from '@/components/Ring'

type Phase = 'info' | 'quiz' | 'done'

// Helper function to shuffle array
const shuffleArray = <T,>(array: T[]): T[] => {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export default function PublicQuizPage() {
  const params = useParams()
  const slug = params.date as string
  const dateKey = slugToDate(slug)
  const mm = slug?.slice(0, 2)
  const dd = slug?.slice(2, 4)

  const [phase, setPhase]         = useState<Phase>('info')
  const [name, setName]           = useState('')
  const [questions, setQuestions] = useState<QuizQuestion[]>([])
  const [shuffledQuestions, setShuffledQuestions] = useState<Array<QuizQuestion & { shuffled_options: string[] }>>([])
  const [answers, setAnswers]     = useState<Record<number, string>>({})
  const [qi, setQi]               = useState(0)
  const [revealed, setRevealed]   = useState(false)
  const [score, setScore]         = useState(0)
  const [err, setErr]             = useState('')
  const [busy, setBusy]           = useState(false)

  const start = useCallback(async () => {
    if (!name.trim()) {
      setErr('Please enter your name'); return
    }

    setBusy(true); setErr('')

    // Try question_forms first (generated by DB trigger)
    const { data: forms } = await supabase
      .from('question_forms').select('questions').eq('form_date', dateKey)

    let rawQuestions: QuizQuestion[]

    if (forms?.length) {
      rawQuestions = forms[0].questions as QuizQuestion[]
    } else {
      // Fallback: build questions directly from daily_words
      const { data: words } = await supabase
        .from('daily_words').select('*').eq('word_date', dateKey)

      if (!words?.length) {
        setErr('No quiz found for this date.')
        setBusy(false); return
      }
      rawQuestions = buildQuestions(words)
    }

    // Shuffle options for each question
    const shuffled = rawQuestions.map(q => ({
      ...q,
      shuffled_options: shuffleArray(q.options)
    }))

    setQuestions(rawQuestions)
    setShuffledQuestions(shuffled)
    setPhase('quiz')
    setBusy(false)
  }, [name, dateKey])

  const pick = (opt: string) => { if (revealed) return; setAnswers(p => ({ ...p, [qi]: opt })) }

  const next = async () => {
    setRevealed(false)
    if (qi + 1 < questions.length) { setQi(q => q + 1); return }
    
    let s = 0
    questions.forEach((q, i) => { if (answers[i] === q.correct_answer) s++ })
    setScore(s)
    setPhase('done')
  }

  const restart = () => {
    setPhase('info')
    setName('')
    setAnswers({})
    setQi(0)
    setRevealed(false)
    setScore(0)
    setErr('')
  }

  const q = shuffledQuestions[qi]
  const pct = questions.length ? Math.round((score / questions.length) * 100) : 0
  const scoreColor = pct >= 80 ? 'var(--emerald)' : pct >= 60 ? 'var(--gold)' : 'var(--danger)'

  return (
    <div style={{ maxWidth: 540, margin: '0 auto', padding: '32px 20px' }} className="au">

      {/* ── ENTER NAME ── */}
      {phase === 'info' && (
        <div className="card">
          <div style={{ textAlign: 'center', marginBottom: 28 }}>
            <div style={{ fontSize: 44, marginBottom: 12 }}>📚</div>
            <h1 style={{ fontSize: 22, fontWeight: 800, marginBottom: 4 }}>Word Quiz</h1>
            <div style={{ color: 'var(--sub)', fontSize: 13, marginTop: 8 }}>
              Date: <strong style={{ color: 'var(--text)' }}>{mm}/{dd}</strong>
            </div>
          </div>

          {err && <div className="err-box">{err}</div>}

          <label>Your Name</label>
          <input className="input" placeholder="e.g. Aung Aung" value={name}
            onChange={e => { setName(e.target.value); setErr('') }}
            onKeyDown={e => e.key === 'Enter' && name.trim() && start()}
            style={{ marginBottom: 20 }} />

          <button className="btn btn-p" style={{ width: '100%' }} onClick={start} disabled={busy || !name.trim()}>
            {busy ? <span className="spin">⟳</span> : 'Start Quiz →'}
          </button>

          <div style={{ marginTop: 16, padding: '12px 14px', background: 'rgba(124,92,252,.07)', borderRadius: 10, fontSize: 12, color: 'var(--sub)' }}>
            ✨ No account needed — just enter your name and start learning!
          </div>
        </div>
      )}

      {/* ── QUIZ ── */}
      {phase === 'quiz' && q && (
        <div className="au">
          {/* Progress bar */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
            <span className="badge bp">Q {qi + 1} / {questions.length}</span>
            <div style={{ fontSize: 13, color: 'var(--sub)' }}>{name}</div>
          </div>

          <div style={{ height: 4, background: '#1A1D2E', borderRadius: 2, marginBottom: 24 }}>
            <div style={{ height: '100%', background: 'var(--accent)', borderRadius: 2, width: `${(qi / questions.length) * 100}%`, transition: 'width .4s' }} />
          </div>

          {/* Question */}
          <div className="card" style={{ marginBottom: 18, borderColor: 'rgba(124,92,252,.35)' }}>
            <div style={{ fontSize: 11, color: 'var(--accent-lt)', fontWeight: 700, marginBottom: 8, textTransform: 'uppercase', letterSpacing: '.5px' }}>📖 {q.word}</div>
            <div style={{ fontSize: 17, fontWeight: 600, lineHeight: 1.55 }}>{q.question}</div>
          </div>

          {/* Options */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
            {q.shuffled_options.map((opt, i) => {
              let cls = 'opt'
              if (revealed) {
                if (opt === q.correct_answer) cls += ' ok'
                else if (opt === answers[qi]) cls += ' bad'
              } else if (answers[qi] === opt) cls += ' sel'
              return (
                <button key={i} className={cls} disabled={revealed} onClick={() => pick(opt)}>
                  <span style={{ color: 'var(--sub)', marginRight: 10 }}>{String.fromCharCode(65 + i)}.</span>{opt}
                </button>
              )
            })}
          </div>

          <div style={{ marginTop: 18 }}>
            {!revealed
              ? <button className="btn btn-p" style={{ width: '100%' }} disabled={!answers[qi]} onClick={() => setRevealed(true)}>Check Answer</button>
              : <button className="btn btn-g" style={{ width: '100%' }} onClick={next} disabled={busy}>
                  {busy ? <span className="spin">⟳</span> : qi + 1 < questions.length ? 'Next Question →' : 'See Results 🎉'}
                </button>
            }
          </div>
        </div>
      )}

      {/* ── RESULTS ── */}
      {phase === 'done' && (
        <div className="card au" style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>
            {pct >= 80 ? '🏆' : pct >= 60 ? '👍' : '📚'}
          </div>

          <div>
            <h2 style={{ fontSize: 22, fontWeight: 800, marginBottom: 4 }}>Quiz Complete!</h2>
            <div style={{ color: 'var(--sub)', fontSize: 14 }}>{name} · {mm}/{dd}</div>
          </div>

          <div style={{ display: 'flex', justifyContent: 'center', marginTop: 24, marginBottom: 24 }}>
            <Ring pct={pct} size={140} color={scoreColor} label={`${score}/${questions.length || 5}`} sub="score" />
          </div>

          <div style={{ background: 'var(--bg)', borderRadius: 14, padding: '16px 20px', marginBottom: 24, textAlign: 'left' }}>
            {[
              ['Correct answers', score, 'var(--emerald)'],
              ['Total questions', questions.length || 5, 'var(--text)'],
              ['Percentage', `${pct}%`, scoreColor],
            ].map(([l, v, c]) => (
              <div key={String(l)} style={{ display: 'flex', justifyContent: 'space-between', padding: '7px 0', borderBottom: '1px solid var(--border)' }}>
                <span style={{ color: 'var(--sub)', fontSize: 13 }}>{l}</span>
                <strong style={{ color: String(c) }}>{v}</strong>
              </div>
            ))}
          </div>

          <button className="btn btn-g" style={{ width: '100%', marginBottom: 10 }} onClick={restart}>
            ↻ Try Again
          </button>
          <a href="/" className="btn btn-gh" style={{ width: '100%', display: 'flex', justifyContent: 'center' }}>
            ← Back Home
          </a>
        </div>
      )}
    </div>
  )
}
